# -*- coding: utf-8 -*-
"""filmes_dataframe_HEITORQUEAND.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sgYlYB9NGN6s1zqgqgZelAjjMFkJ85QM

# QUESTÃO 1
"""

import pandas as pd

dados = {
    'Nome': ['Vingadores: Ultimato', 'O Senhor dos Anéis: O Retorno do Rei', 'Que Horas Ela Volta', 'A Viagem de Chihiro', 'O Poderoso Chefão', '1917', 'Avatar'],
    'Diretor': ['Anthony e Joe Russo', 'Peter Jackson', 'Anna Muylaert', 'Hayao Miyazaki', 'Francis Ford Coppola', 'Sam Mendes', 'James Cameron'],
    'Gênero': ['Ação', 'Fantasia', 'Drama', 'Animação', 'Drama', 'Guerra', 'Ação/Ficção científica'],
    'Duração em horas': [3, 3.2, 1.5, 2.5, 2.5, 1.5, 2.4],
    'Ator principal': ['Robert Downey Jr.', 'Elijah Wood', 'Regina Casé', 'Rumi Hiiragi', 'Marlon Brando', 'George MacKay', 'Sam Worthington'],
    'Nota do IMDb': [8.4, 8.9, 7.7, 8.6, 9.2, 8.3, 7.9]
}

filmes_df = pd.DataFrame(dados)
display (filmes_df)

"""# QUESTÃO 2"""

# Apresentando o tamanho:
tamanho = filmes_df.shape
print(f"Tamanho do DataFrame: {tamanho[0]} linhas x {tamanho[1]} colunas")

"""# QUESTÃO 3"""

# Apresentando a linha
x = 2
linhaX = filmes_df.iloc[x]
display (linhaX)

"""# QUESTÃO 4"""

# Apresentar se o codigo está vazio:
vazio = filmes_df.empty
print(f"O dataframe é vazio? {vazio}")

"""# QUESTÃO 5"""

# Apresentando 5 primeiros registros:
cincoReg= filmes_df.head(5)
display(cincoReg)

"""# QUESTÃO 6"""

# Exclui a linha onde o nome do filme é 'Avatar'
filmes_df.drop(filmes_df[filmes_df['Nome'] == 'Avatar'].index, axis=0, inplace=True)
display(filmes_df)

"""# QUESTÃO 7"""

# Adicionando novo filme
novoFilme = {
    'Nome': 'O Homem do Futuro',
    'Diretor': 'Cláudio Torres',
    'Gênero': 'Comédia',
    'Duração em horas': 1.5,
    'Ator principal': 'Wagner Moura',
    'Nota do IMDb': 7.0
}

novoFilme_df = pd.DataFrame([novoFilme])

filmes_df = pd.concat([filmes_df, novoFilme_df], ignore_index=True)

display(filmes_df)

"""# QUESTÃO 8"""

# Transpondo a coluna
filmesTransp = filmes_df.transpose()
display(filmesTransp)

"""# QUESTÃO 9"""

# Apresentando colunas 0 até 2(: antes da virgulha é linhas e depois é a quantidade de colunas no caso do exemplo :,:2 respectivamente todas as linhas e duas colunas)
colunasSelec = filmes_df.iloc[:, :2]
display(colunasSelec)

"""# Questão 10
Primeiramente, utilizando a biblioteca de software pandas e a IDE do proprio Google Collab foi criado um dataframe sobre filmes indicando nome, diretor, duração entre outras informações

Após isso para completar a segunda questão eu utilizei o comando shape para que fosse mostrado o tamanho do meu dataframe sendo "tamanho[0]" representando o numero de linhas e "tamanho[1]" representando o numero de colunas.

Para a terceira questão foi expecificado primeiramente um numero para que fosse definido qual linha ele iria buscar e com isso utilizamos o "iloc[x]" para que fosse apresentando a linha correspondente ao x (2 ou Que Horas Ela Volta).

Para a quarta questão utilizamos o empty para dizer se o dataframe é vazio ou não, retornando um valor boleano.

Para a quinta questão utilizamos o head(5) para especificar quais linhas queremos apresentar em nosso output (neste caso sendo as 5 primeiras linhas)

Para a sexta questão utilizamos o drop para apagar o filme Avatar.

Para a setima questão criamos um novo dataframe com o filme que gostaremos de inserir no dataframe principal. E para uni-los utilizamos o comando concat para que possam ser "concatenados"

Para a oitava questão utilizamos o transpose para trocarmos as linhas e colunas de lugar invertendo seu design

Para a nona questão utilizamos o iloc novamente para escolhermos quais colunas e quais linhas iremos apresentar sendo respectivament e apresentanda colunas 0 até 2 (: antes da virgulha é linhas e depois é a quantidade de colunas no caso do exemplo :,:2 respectivamente todas as linhas e duas colunas)
"""