# -*- coding: utf-8 -*-
"""filmes_dataframe_HEITORQUEAND.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sgYlYB9NGN6s1zqgqgZelAjjMFkJ85QM

# QUESTÃO 1
"""

import pandas as pd

dados = {
    'Nome': ['Vingadores: Ultimato', 'O Senhor dos Anéis: O Retorno do Rei', 'Que Horas Ela Volta', 'A Viagem de Chihiro', 'O Poderoso Chefão', '1917', 'Avatar'],
    'Diretor': ['Anthony e Joe Russo', 'Peter Jackson', 'Anna Muylaert', 'Hayao Miyazaki', 'Francis Ford Coppola', 'Sam Mendes', 'James Cameron'],
    'Gênero': ['Ação', 'Fantasia', 'Drama', 'Animação', 'Drama', 'Guerra', 'Ação/Ficção científica'],
    'Duração em horas': [3, 3.2, 1.5, 2.5, 2.5, 1.5, 2.4],
    'Ator principal': ['Robert Downey Jr.', 'Elijah Wood', 'Regina Casé', 'Rumi Hiiragi', 'Marlon Brando', 'George MacKay', 'Sam Worthington'],
    'Nota do IMDb': [8.4, 8.9, 7.7, 8.6, 9.2, 8.3, 7.9]
}

filmes_df = pd.DataFrame(dados)
display (filmes_df)

"""# QUESTÃO 2"""

# Apresentando o tamanho:
tamanho = filmes_df.shape
print(f"Tamanho do DataFrame: {tamanho[0]} linhas x {tamanho[1]} colunas")

"""# QUESTÃO 3"""

# Apresentando a linha
x = 2
linhaX = filmes_df.iloc[x]
display (linhaX)

"""# QUESTÃO 4"""

# Apresentar se o codigo está vazio:
vazio = filmes_df.empty
print(f"O dataframe é vazio? {vazio}")

"""# QUESTÃO 5"""

# Apresentando 5 primeiros registros:
cincoReg= filmes_df.head(5)
display(cincoReg)

"""# QUESTÃO 6"""

# Exclui a linha onde o nome do filme é '1917'
excluir = filmes_df[filmes_df['Nome'] != 'Avatar']
display(excluir)

"""# QUESTÃO 7"""

# Adicionando novo filme
novoFilme = {
    'Nome': 'O Homem do Futuro',
    'Diretor': 'Cláudio Torres',
    'Gênero': 'Comédia',
    'Duração em horas': 1.5,
    'Ator principal': 'Wagner Moura',
    'Nota do IMDb': 7.0
}

novoFilme_df = pd.DataFrame([novoFilme])

filmes_df = pd.concat([filmes_df, novoFilme_df], ignore_index=True)

display(filmes_df)

"""# QUESTÃO 8"""

# Transpondo a coluna
filmesTransp = filmes_df.transpose()
display(filmesTransp)

"""# QUESTÃO 9"""

# Apresentando colunas 0 até 2(: antes da virgulha é linhas e depois é a quantidade de colunas no caso do exemplo :,:2 respectivamente todas as linhas e duas colunas)
colunasSelec = filmes_df.iloc[:, :2]
display(colunasSelec)